# Generated by Django 3.2.19 on 2023-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'no checking account'), (2, '... < 0 DM'), (3, '0 <= ... < 200 DM'), (4, '... >= 200 DM / salary assignments for at least 1 year')], max_length=100)),
                ('duration', models.IntegerField()),
                ('credit_history', models.CharField(choices=[(0, 'critical account/ other credits existing (not at this bank)'), (1, 'delay in paying off in the past'), (2, 'existing credits paid back duly till now'), (3, 'all credits at this bank paid back duly'), (4, 'no credits taken/ all credits paid back duly')], max_length=100)),
                ('purpose', models.CharField(choices=[(0, 'OTHERS'), (1, 'CAR (NEW)'), (2, 'CAR (USED)'), (3, 'FURNITURE/EQUIPMENT'), (4, 'RADIO/TELEVISION'), (5, 'DOMESTIC APPLIANCES'), (6, 'REPAIRS'), (7, 'EDUCATION'), (8, 'VACATION'), (9, 'RETRAINING'), (10, 'BUSINESS')], max_length=100)),
                ('amount', models.IntegerField()),
                ('savings', models.CharField(choices=[(1, 'UNKNOWN/NO SAVINGS ACCOUNT'), (2, '... < 100 DM'), (3, '100 <= ... < 500 DM'), (4, '500 <= ... < 1000 DM'), (5, '... >= 1000 DM')], max_length=100)),
                ('employment_duration', models.CharField(choices=[(1, 'Unemployed'), (2, '... < 1 year'), (3, '1 <= ... < 4 years'), (4, '4 <= ... < 7 years'), (5, '.. >= 7 years')], max_length=100)),
                ('installment_rate', models.CharField(choices=[(1, '>= 35'), (2, '25 <= ...'), (3, '20 <= ... '), (4, '< 20')], max_length=100)),
                ('personal_status_sex', models.CharField(choices=[(1, 'Male: divorced/separated'), (2, 'Female: divorced/separated/married'), (3, 'Male: single'), (4, 'Male: married/widowed'), (5, 'Female: single')], max_length=100)),
                ('property', models.CharField(choices=[(1, 'UNKNOWN / NO PROPERTY'), (2, 'CAR OR OTHER'), (3, 'BUILDING SOC. SAVINGS AGR./LIFE INSURANCE'), (4, 'REAL ESTATE')], max_length=100)),
                ('age', models.IntegerField()),
                ('number_credits', models.CharField(choices=[(1, '1'), (2, '2-3'), (3, '4-5'), (4, '>=6')], max_length=100)),
                ('job', models.CharField(choices=[(1, 'unemployed/ unskilled - non-resident'), (2, 'unskilled - resident'), (3, 'skilled employee / official'), (4, 'management/ self-employed/highly qualified employee/ officer')], max_length=100)),
                ('people_liable', models.IntegerField()),
                ('telephone', models.CharField(choices=[(1, 'No'), (2, "Yes, registered under the customer's name")], max_length=100)),
                ('credit_risk', models.IntegerField()),
            ],
        ),
    ]
