# Generated by Django 3.2.19 on 2023-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='iin',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
