# Generated by Django 3.2.19 on 2023-06-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_auto_20230603_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Тұтынушы', 'verbose_name_plural': 'Тұтынушылар'},
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(verbose_name='Жасы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='amount',
            field=models.IntegerField(verbose_name='Сомасы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_history',
            field=models.CharField(choices=[('0', 'Басқа банктерде несиелері бар'), ('1', 'Бұрында несиені уақытылы төлемеген'), ('2', 'Қазіргі несиелерді тиісті түрде төлеуде'), ('3', 'Осы банктегі барлық несиелері тиісті түрде қайтарылды'), ('4', 'Несие алмаған/ барлық несиелер тиісті түрде қайтарылған')], max_length=100, verbose_name='Кредит тарихы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_risk',
            field=models.IntegerField(verbose_name='Несиелік қабілеті'),
        ),
        migrations.AlterField(
            model_name='client',
            name='duration',
            field=models.IntegerField(verbose_name='Кредиттеу мерзімі'),
        ),
        migrations.AlterField(
            model_name='client',
            name='employment_duration',
            field=models.CharField(choices=[('1', 'Жұмыссыз'), ('2', '... < 1 жыл'), ('3', '1 жыл<= ... < 4 жыл'), ('4', '4 жыл<= ... < 7 жыл'), ('5', '.. >= 7 жыл')], max_length=100, verbose_name='Жұмыс істеу мерзімі'),
        ),
        migrations.AlterField(
            model_name='client',
            name='iin',
            field=models.CharField(default='0', max_length=100, verbose_name='ЖСН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='installment_rate',
            field=models.CharField(choices=[('1', '>= 35%'), ('2', '25% <= ...'), ('3', '20% <= ... '), ('4', '< 20%')], max_length=100, verbose_name='Сыйақы мөлшерлемелері'),
        ),
        migrations.AlterField(
            model_name='client',
            name='job',
            field=models.CharField(choices=[('1', 'жұмыссыз/ білікті емес - резидент емес'), ('2', 'білікті емес – резидент'), ('3', 'білікті қызметкер/шенеунік'), ('4', 'басшы/ өзін-өзі жұмыспен қамтыған/жоғары білікті қызметкер/ офицер')], max_length=100, verbose_name='Жұмысы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Аты-жөні'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_credits',
            field=models.CharField(choices=[('1', '1'), ('2', '2-3'), ('3', '4-5'), ('4', '>=6')], max_length=100, verbose_name='Несиелерінің саны'),
        ),
        migrations.AlterField(
            model_name='client',
            name='people_liable',
            field=models.IntegerField(verbose_name='Жауапты адамдар'),
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_status_sex',
            field=models.CharField(choices=[('1', 'Еркек: ажырасқан'), ('2', 'Әйел: ажырасқан'), ('3', 'Еркек: бойдақ'), ('4', 'Ер адам/Әйел: үйленген'), ('5', 'Әйел: жалғызбасты')], max_length=100, verbose_name='Жеке статусы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='property',
            field=models.CharField(choices=[('1', 'БЕЛГІСІЗ / МҮЛІК ЖОҚ'), ('2', 'КӨЛІК НЕМЕСЕ БАСҚА'), ('3', 'МҮЛІГІ БАР, ӨМІР САҚТАНДЫРУ'), ('4', 'ЖЫЛЖЫМАЙТЫН МҮЛІК')], max_length=100, verbose_name='Мүлігі'),
        ),
        migrations.AlterField(
            model_name='client',
            name='purpose',
            field=models.CharField(choices=[('0', 'БАСҚА'), ('1', 'КӨЛІК (ЖАҢА)'), ('2', 'КӨЛІК (ПАЙДАЛАНҒАН)'), ('3', 'ЖИБАЗ/ЖАБДЫҚ'), ('4', 'ТҰРМЫСТЫҚ ТЕХНИКА'), ('5', 'ТҰРМЫСТЫҚ ҚҰРАЛДАР'), ('6', 'ЖӨНДЕУ'), ('7', 'ОҚУ'), ('8', 'ДЕМАЛЫС'), ('9', 'КВАЛИФИКАЦИЯ КӨТЕРУ'), ('10', 'БИЗНЕС')], max_length=100, verbose_name='Мақсаты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='savings',
            field=models.CharField(choices=[('1', 'БЕЛГІСІЗ/ЖИНАҚ ШОТЫ ЖОҚ'), ('2', '... < 50 000₸'), ('3', '50 000₸<= ... < 300 000₸'), ('4', '300 000₸ <= ... < 600 000₸'), ('5', '... >= 600 000₸')], max_length=100, verbose_name='Сақталған қаржысы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('1', 'Шоты жоқ'), ('2', '... < 0₸'), ('3', '0₸ <= ... < 100 000₸'), ('4', '... >= 100 000₸ және расталған жалақысы бар')], max_length=100, verbose_name='Шот статусы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(choices=[('1', 'Жоқ'), ('2', 'Иә, тұтынушының атына тіркелген')], editable=False, max_length=100, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Түсініктеме')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Күні')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.client')),
            ],
            options={
                'verbose_name': 'Тұтынушы бойынша есеп',
                'verbose_name_plural': 'Тұтынушылар бойына есептер',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Түсініктеме')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Күні')),
                ('is_black', models.BooleanField(default=False, verbose_name='Қара тізімде ме?')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.client')),
            ],
            options={
                'verbose_name': 'Қара тізім',
                'verbose_name_plural': 'Қара тізім',
            },
        ),
    ]
