# Generated by Django 3.2.19 on 2023-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20230604_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_score',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Несиелік қабілетінің ұпайы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_risk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Несиелік қабілеті'),
        ),
    ]
