# Generated by Django 3.2.19 on 2023-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_auto_20230604_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_creditable',
            field=models.CharField(choices=[('БЕЛГІСІЗ', 'Белгісіз'), ('ЖОҚ', 'Жоқ'), ('ИӘ', 'Иә')], default='БЕЛГІСІЗ', max_length=100, verbose_name='Несие ала алады ма?'),
        ),
    ]
